"""
LenQredZo AI — Analysis Microservice
A small FastAPI service that turns anonymized loan-portfolio statistics into
plain-language insights using Google's Gemini API.

PRIVACY BY DESIGN: This service accepts ONLY aggregated, anonymized numbers
(totals, counts, percentages). It never receives or sends customer names,
phone numbers, Aadhaar, PAN, or any other personally identifiable information.

SECURITY: The /analyze endpoint requires a shared internal key (X-Internal-Key
header) that only the Node backend knows, so the public/browser cannot call it
directly and run up Gemini usage. The Gemini API key itself stays server-side.
"""

import os
from fastapi import FastAPI, HTTPException, Header, Depends
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from dotenv import load_dotenv

load_dotenv()

import re

# Detects obvious personal/sensitive identifiers so they are never sent to Gemini.
AADHAAR_RE = re.compile(r'\b\d{4}\s?\d{4}\s?\d{4}\b')   # 12 digits (optionally spaced)
PAN_RE = re.compile(r'\b[A-Za-z]{5}\d{4}[A-Za-z]\b')    # ABCDE1234F
PHONE_RE = re.compile(r'\b[6-9]\d{9}\b')                # Indian 10-digit mobile

def contains_pii(text: str):
    if not text:
        return None
    if AADHAAR_RE.search(text):
        return "what looks like an Aadhaar number"
    if PAN_RE.search(text):
        return "what looks like a PAN"
    if PHONE_RE.search(text):
        return "what looks like a phone number"
    return None

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")
INTERNAL_API_KEY = os.getenv("INTERNAL_API_KEY", "")

DISCLAIMER = (
    "AI-generated by Google Gemini. These are automated suggestions based only on the "
    "summary numbers provided — they may be incomplete or inaccurate, are NOT financial, "
    "legal, or lending advice, and should be verified by a qualified person before any decision. "
    "Do NOT enter any customer personal or sensitive details (names, phone numbers, Aadhaar, "
    "PAN, or addresses) — share only aggregate numbers with this tool."
)



app = FastAPI(title="LenQredZo AI Analysis Service", version="1.0.0")

# No browser origins are allowed — all calls must come server-to-server from the Node API.
app.add_middleware(
    CORSMiddleware,
    allow_origins=[],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ---- Internal auth: only callers that know the shared secret may use /analyze ----
def verify_internal_key(x_internal_key: str = Header(default="")):
    if not INTERNAL_API_KEY:
        # Fail closed: if the secret isn't configured, refuse rather than run open.
        raise HTTPException(status_code=500, detail="INTERNAL_API_KEY is not configured on the AI service.")
    if x_internal_key != INTERNAL_API_KEY:
        raise HTTPException(status_code=401, detail="Unauthorized: invalid or missing internal key.")


# ---- Input model: ONLY anonymized aggregate stats are accepted (no PII fields exist) ----
class PortfolioStats(BaseModel):
    total_disbursed: float = 0
    total_collected: float = 0
    active_loans: int = 0
    total_customers: int = 0
    overdue_emis: int = 0
    overdue_amount: float = 0
    npa_percentage: float = 0
    collection_efficiency: float = 0
    high_risk_customers: int = 0


class AnalyzeRequest(BaseModel):
    prompt_type: str = Field(default="portfolio_health")
    stats: PortfolioStats
    question: str = ""  # used only when prompt_type == "custom"


def build_prompt(prompt_type: str, stats: PortfolioStats, question: str) -> str:
    facts = (
        "Here are anonymized summary numbers for a small lending business:\n"
        f"- Total disbursed: INR {stats.total_disbursed:,.0f}\n"
        f"- Total collected: INR {stats.total_collected:,.0f}\n"
        f"- Active loans: {stats.active_loans}\n"
        f"- Total customers: {stats.total_customers}\n"
        f"- Overdue EMIs: {stats.overdue_emis}\n"
        f"- Overdue amount: INR {stats.overdue_amount:,.0f}\n"
        f"- NPA (non-performing assets): {stats.npa_percentage}%\n"
        f"- Collection efficiency: {stats.collection_efficiency}%\n"
        f"- High-risk customers: {stats.high_risk_customers}\n"
    )

    presets = {
        "portfolio_health": (
            "You are a financial analyst. Based ONLY on the numbers below, write a short, "
            "plain-language health check of this loan portfolio for a non-expert owner. "
            "Cover what looks good, what looks risky, and 2-3 practical next steps. "
            "Keep it under 200 words. Do not invent numbers that are not given.\n\n" + facts
        ),
        "risk_assessment": (
            "You are a credit-risk analyst. Based ONLY on the numbers below, summarize the "
            "main risks in this loan portfolio and explain in simple terms what they mean. "
            "Keep it under 200 words. Do not invent data.\n\n" + facts
        ),
        "collection_strategy": (
            "You are a collections advisor. Based ONLY on the numbers below, suggest 3-5 "
            "practical, ethical steps a small lender could take to improve collections and "
            "reduce overdue amounts. Keep it under 200 words. Do not invent data.\n\n" + facts
        ),
    }

    if prompt_type == "custom":
        safe_q = question.strip() or "Give a brief overview of this portfolio."
        return (
            "You are a financial analyst. Answer the owner's question using ONLY the numbers "
            "below. If the numbers cannot answer it, say so honestly. Keep it under 200 words. "
            "Do not invent data.\n\n"
            f"Owner's question: {safe_q}\n\n" + facts
        )

    return presets.get(prompt_type, presets["portfolio_health"])


@app.get("/")
def health():
    # Public health check — exposes no secrets, only whether keys are configured.
    return {
        "service": "LenQredZo AI Analysis",
        "status": "running",
        "model": GEMINI_MODEL,
        "gemini_key_configured": bool(GEMINI_API_KEY),
        "internal_key_configured": bool(INTERNAL_API_KEY),
    }


@app.get("/prompts")
def list_prompts():
    return {
        "prompt_types": [
            {"id": "portfolio_health", "label": "Portfolio Health Check"},
            {"id": "risk_assessment", "label": "Risk Assessment"},
            {"id": "collection_strategy", "label": "Collection Strategy"},
            {"id": "custom", "label": "Ask a custom question"},
        ]
    }


@app.post("/analyze", dependencies=[Depends(verify_internal_key)])
def analyze(req: AnalyzeRequest):
    if not GEMINI_API_KEY:
        raise HTTPException(status_code=500, detail="GEMINI_API_KEY is not set on the AI service.")
    found = contains_pii(req.question)
    if found:
        raise HTTPException(
            status_code=400,
            detail=f"Your question contains {found}. Please remove any personal/sensitive customer details — share only aggregate numbers."
        )
    prompt = build_prompt(req.prompt_type, req.stats, req.question)

    try:
        from google import genai
        client = genai.Client(api_key=GEMINI_API_KEY)
        response = client.models.generate_content(model=GEMINI_MODEL, contents=prompt)
        text = (response.text or "").strip()
    except Exception as e:
        raise HTTPException(status_code=502, detail=f"Gemini request failed: {e}")

    return {
        "prompt_type": req.prompt_type,
        "model": GEMINI_MODEL,
        "insight": text,
        "disclaimer": DISCLAIMER,
    }